# Generated by Django 5.2 on 2025-05-16 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccredReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('ELEX', 'ELEX'), ('CIVL', 'CIVL'), ('MECH', 'MECH'), ('MINE', 'MINE')], max_length=4)),
                ('term', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('ga', models.CharField(choices=[('GA1', 'GA1'), ('GA2', 'GA2'), ('GA3', 'GA3'), ('GA4', 'GA4'), ('GA5', 'GA5'), ('GA6', 'GA6'), ('GA7', 'GA7'), ('GA8', 'GA8'), ('GA9', 'GA9'), ('GA10', 'GA10'), ('GA11', 'GA11'), ('GA12', 'GA12')], max_length=4)),
                ('gai', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('12.1', '12.1'), ('12.2', '12.2'), ('12.3', '12.3'), ('12.4', '12.4')], max_length=4)),
                ('assess_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Project', 'Project'), ('Lab report', 'Lab report'), ('Presentation', 'Presentation'), ('Peer-Assessment', 'Peer-Assessment'), ('Final exam', 'Final exam'), ('Mid-term', 'Mid-term'), ('Quiz', 'Quiz'), ('Homework', 'Homework'), ('Self-Assessment', 'Self-Assessment'), ('Other', 'Other')], max_length=15)),
                ('quest_text', models.CharField(max_length=400)),
                ('alignment', models.CharField(choices=[('Perfectly', 'Perfectly'), ('Highly', 'Highly'), ('Mostly', 'Mostly'), ('Somewhat', 'Somewhat')], max_length=9)),
                ('instr_level', models.CharField(choices=[('Introductory', 'Introductory'), ('Intermediate Development', 'Intermediate Development'), ('Advanced Application', 'Advanced Application')], max_length=24)),
                ('achievement_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_id', models.CharField(max_length=9, validators=[django.core.validators.MinValueValidator(9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('ELEX', 'ELEX'), ('CIVL', 'CIVL'), ('MECH', 'MECH'), ('MINE', 'MINE')], max_length=4)),
                ('term', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('course', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('ga', models.CharField(choices=[('GA1', 'GA1'), ('GA2', 'GA2'), ('GA3', 'GA3'), ('GA4', 'GA4'), ('GA5', 'GA5'), ('GA6', 'GA6'), ('GA7', 'GA7'), ('GA8', 'GA8'), ('GA9', 'GA9'), ('GA10', 'GA10'), ('GA11', 'GA11'), ('GA12', 'GA12')], max_length=4)),
                ('gai', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('12.1', '12.1'), ('12.2', '12.2'), ('12.3', '12.3'), ('12.4', '12.4')], max_length=4)),
                ('student_id', models.CharField(max_length=9, validators=[django.core.validators.MinValueValidator(9)])),
                ('achievement_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assess_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Project', 'Project'), ('Lab report', 'Lab report'), ('Presentation', 'Presentation'), ('Peer-Assessment', 'Peer-Assessment'), ('Final exam', 'Final exam'), ('Mid-term', 'Mid-term'), ('Quiz', 'Quiz'), ('Homework', 'Homework'), ('Self-Assessment', 'Self-Assessment'), ('Other', 'Other')], max_length=15)),
                ('instr_comments', models.CharField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessValidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gai', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('12.1', '12.1'), ('12.2', '12.2'), ('12.3', '12.3'), ('12.4', '12.4')], max_length=4)),
                ('ga', models.CharField(choices=[('GA1', 'GA1'), ('GA2', 'GA2'), ('GA3', 'GA3'), ('GA4', 'GA4'), ('GA5', 'GA5'), ('GA6', 'GA6'), ('GA7', 'GA7'), ('GA8', 'GA8'), ('GA9', 'GA9'), ('GA10', 'GA10'), ('GA11', 'GA11'), ('GA12', 'GA12')], max_length=4)),
                ('course', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('question_max', models.IntegerField()),
                ('alignment', models.CharField(choices=[('Perfectly', 'Perfectly'), ('Highly', 'Highly'), ('Mostly', 'Mostly'), ('Somewhat', 'Somewhat')], max_length=9)),
                ('gai_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('assess_max', models.IntegerField()),
                ('assess_weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('assess_descript', models.CharField(max_length=200)),
                ('clos', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('program', models.CharField(choices=[('ELEX', 'ELEX'), ('CIVL', 'CIVL'), ('MECH', 'MECH'), ('MINE', 'MINE')], max_length=4)),
                ('course', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('gai', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('12.1', '12.1'), ('12.2', '12.2'), ('12.3', '12.3'), ('12.4', '12.4')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('term', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('instr_first_name', models.CharField(max_length=20)),
                ('instr_last_name', models.CharField(max_length=20)),
                ('assess_title', models.CharField(max_length=12)),
                ('gai_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('cohort', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('ga', models.CharField(choices=[('GA1', 'GA1'), ('GA2', 'GA2'), ('GA3', 'GA3'), ('GA4', 'GA4'), ('GA5', 'GA5'), ('GA6', 'GA6'), ('GA7', 'GA7'), ('GA8', 'GA8'), ('GA9', 'GA9'), ('GA10', 'GA10'), ('GA11', 'GA11'), ('GA12', 'GA12')], max_length=4)),
                ('gai', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('12.1', '12.1'), ('12.2', '12.2'), ('12.3', '12.3'), ('12.4', '12.4')], max_length=4)),
                ('gai_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('achievement_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cohort', models.CharField(max_length=11)),
                ('prog_term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_uploaded', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
